[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
iced = { version = "0.13", features = ["tokio", "advanced","image"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "uuid"] }
shared = { path = "../shared" }
tokio-tungstenite = "0.21"
url = "2.5"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
futures-util = "0.3"
rfd = "0.14"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
base64 = "0.22"
notify-rust = "4"
rodio = "0.19"

[package.metadata.appimage]
assets = "appimage"
